### PR TITLE
Fixed stylesheet generation

### PR DESCRIPTION
**Pull request by asgarddesigns**
Only difference I can see now is the newline break between each file 'block'.

I can look into getting rid of that too when I have some time.

### CODE REVIEW

**Comment by asgarddesigns** [comment]
Also tested with some NPM dependency css files and fixed issues around that.

**Comment by nareshbhatia** [comment]
Thanks Ben.

Could you please revert the changes on README.md? There are lines in there marked "<<<<<<HEAD" etc. - I am guessing due to merge conflicts with angular-seed. That's one file that I would like to maintain independent of the angular2-seed project.

**Comment by asgarddesigns** [comment]
Ahh yep, must have missed that file! Should be sorted now.

**Comment by nareshbhatia** [comment]
Thanks, Ben.

**Pull request merged**
