### PR TITLE
Feature/scss lint

### PR DESCRIPTION
**Pull request by asgarddesigns**
On top of the sync (which you might want to PR separately) I have also added linting to sass.

I have also set outputs to the dist directory rather than creating in the source dir to prevent confusion between the separate files. Not sure if that will cause any other issues. Let me know if so and I can at update accordingly.

### CODE REVIEW

**Comment by nareshbhatia** [comment]
Took a quick look at this. Seems to work fine. Quick question, how is the TypeScript compiler able to access .css files in the dist directory?

Also this PR requires ruby and sccs_lint, so README.md needs to be updated.

**Comment by nareshbhatia** [comment]
Ah, it thing I figured it out. It seems that the TypeScript compiler does not need to read the css file. All we need to do is to make sure that the css file is available in the same folder as the compiled js file.

**Comment by taijuten** [comment]
Do you guys get multiple "reloading browser"s with these changes?

**Comment by nareshbhatia** [comment]
Thanks, Ben. Merged.

@taijuten - can you please clarify your question? What do you mean by multiple "reloading browsers"?

**Comment by nareshbhatia** [comment]
@asgarddesigns, this PR has caused a break in the prod build. There are two issues, I fixed one, but haven't looked into the second one yet.

The first issue was that the component `.ts` files need to inline the .css files in the `tmp` directory. So I had to output them in the `tmp` instead of `dist/prod`.

The second issue is that all style sheets that are not part of components need to be concatenated and output in `dist/prod/css/all.css`. See the build process in the original angular2-seed project. That process also adds the following lines to `index.html` which picks up the concatenated css file:

```
  <!-- inject:css -->
  <link rel="stylesheet" href="/css/all.css?1459289107856">
  <!-- endinject -->
```

Could you please take a look at this issue?

**Comment by asgarddesigns** [comment]
Yep, can do. May be over the weekend, see how I go for time!

**Comment by nareshbhatia** [comment]
Ok, thanks.

**Pull request merged**
